# Generated by Django 3.2.3 on 2021-05-26 00:19

from django.db import migrations, models
import photo_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Uploading date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True)),
                ('width', photo_upload.models.IntegerRangeField(blank=True, default=200)),
                ('height', photo_upload.models.IntegerRangeField(blank=True, default=200)),
            ],
        ),
    ]
