# Generated by Django 3.2.3 on 2021-05-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, default=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, default=250),
            preserve_default=False,
        ),
    ]
