# Generated by Django 3.2.3 on 2021-05-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_upload', '0002_auto_20210524_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Image_Model',
        ),
    ]
